MenuBar=Disabled

[ContentDisplay]
DirectorySizeMode=None

[DetailsMode]
LeftPadding=0
PreviewSize=64
RightPadding=70

[ExtractDialog]
2 screens: Height=1080
2 screens: Width=1280

[General]
AutoExpandFolders=true
BrowseThroughArchives=true
DynamicView=true
FilterBar=true
GlobalViewProps=false
LockPanels=false
RememberOpenedTabs=false
ShowFullPath=true
ShowStatusBar=FullWidth
ShowZoomSlider=true
SortingChoice=CaseInsensitiveSorting
Version=202
ViewPropsTimestamp=2026,1,21,17,14,6.894

[Icons]
Theme=Papirus-Dark

[IconsMode]
IconSize=48
PreviewSize=160

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22

[MainWindow]
MenuBar=Disabled

[Notification Messages]
ConfirmRenameFileType=false

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,directorythumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,opendocumentthumbnail,svgthumbnail,textthumbnail,ffmpegthumbs

[UiSettings]
ColorScheme=CatppuccinMochaMauve
